### ISSUE TITLE
Record Missing Days from Main Data Frames (Complete)

### ISSUE THREAD

**Issue by jeremyknox-ucsb** [Science-for-Nature-and-People/soc-twitter#32]
# Started
- [x] Identify dates for purchased data vs. twitter API manual collection vs. twitter API [automat.R](https://github.com/Science-for-Nature-and-People/soc-twitter/blob/master/automate.R) collection. 
- [x] Plot missing dates and the different data collection methods listed above.

**Comment by jeremyknox-ucsb** [comment]
<img width="1620" alt="missing_dates" src="https://user-images.githubusercontent.com/43891256/64984268-4f9e6800-d877-11e9-83cf-ff397e318a50.png">

**Comment by jeremyknox-ucsb** [comment]
#Complete

**Comment by brunj7** [comment]
script: missing_date_viz.R
