### ISSUE TITLE
Look into quoted retweet

### ISSUE THREAD

**Issue by swood-ecology** [Science-for-Nature-and-People/soc-twitter#37]
Is there quoted retweets in original dataset? Can we compare retweet analysis with quoted vs not with quoted data to see if there's bias?

**Comment by brunj7** [comment]
first check how quoted retweet are stored in our data set

**Comment by brunj7** [comment]
The data we get from the API has a binary field `is_quote` that flags the quoted tweet.

for those tweets, the `text` field will contain the newly added text, with the quoted tweet as an URL. This URL referring to the original tweet is also stored in the field`urls_t.co` and the original text in `quoted_text`

example: 
New tweet quoting: https://twitter.com/UMNswac/status/1177598282626994179
original/quoted tweet: https://t.co/1mffFq3Em2

So far we have not kept those fields, so It won't be possible to reprocess older tweets at this point. The question is do we want to keep the flag moving forward?

**Comment by swood-ecology** [comment]
Thanks for looking into that. I think we should add it back in, in case we want to use it in the future.

**Comment by swood-ecology** [comment]
Plus, if we can quantify the fraction of RTs that are quotes even on a subset of new data then we can use that as a way to guess at error in our results.

**Comment by brunj7** [comment]
Actually the `is_retweet` flag on the API is set as FALSE  for quoted tweets. In other terms, it is a separate category for twitter. This means in our dataset quoted tweets are currently in the `noRT` file.

**Comment by swood-ecology** [comment]
Interesting! So, they would be separate individual tweets? I think that's just something we should note for the methods.

**Comment by brunj7** [comment]
it is a little surprising as they do certainly count those quoted tweets in the retweet total number... we need to think about this a little more...

**Comment by swood-ecology** [comment]
What does that mean they count it in the total number? Like, for an observation there's a separate data field that is something like `retweet_number` and that seems to include the number of quoted tweets? I wonder, given that, if you could guess at the number of quotes for a tweet, if you have the total number of retweets and the content for the non-quote retweets. That would at least allow us to historically document bias.

**Comment by brunj7** [comment]
Implemented writing a csv file with the quoted tweet information as extra columns (see #44 ). The naming convention for those files is `soilcarbon/Twitter/API_csv/rawdata_$DATE.csv`
