### ISSUE TITLE
Fix Old Retweets (Complete)

### ISSUE THREAD

**Issue by jeremyknox-ucsb** [Science-for-Nature-and-People/soc-twitter#38]
# Started
Current is_retweet column has ~72k NAs. Need to look into [is_retweet.R](https://github.com/Science-for-Nature-and-People/soc-twitter/tree/master/pre_processing) to see why this might be.

Old retweets have "RT @XXXX:" at the beginning of retweet and is truncatated at ~120 characters in and ending with "...". Look into changing all retweets to have the same body of text at the original tweet.

**Comment by jeremyknox-ucsb** [comment]
Current WIP script can replace the body of each retweet with the original tweet text.

**Comment by jeremyknox-ucsb** [comment]
Issue with ~72k NAs in is_retweet column comes from line 61 and 62 of is_retweet.R. Swapping these lines fixed the issue.

**Comment by jeremyknox-ucsb** [comment]
- Replace old retweets that started with "RT @xxxx:" and ended with "...", because they were truncated by Twitter, with the the original tweet that was retweeted with [fix_old_retweets.R](https://github.com/Science-for-Nature-and-People/soc-twitter/blob/master/pre_processing/fix_old_retweets.R) 
- [ ] need to run fix_old_retweets.R on master data frame

**Comment by jeremyknox-ucsb** [comment]
@brunj7  requesting review of  [fix_old_retweets.R](https://github.com/Science-for-Nature-and-People/soc-twitter/blob/master/pre_processing/fix_old_retweets.R) to confirm this wants to be run on entire data frame.

**Comment by jeremyknox-ucsb** [comment]
Dates where retweets that started with "RT @xxxx:" and ended with "..."
<img width="1497" alt="Screen Shot 2019-09-23 at 1 18 49 PM" src="https://user-images.githubusercontent.com/43891256/65459498-e5e90580-de04-11e9-9815-25aa2ac8c247.png">

**Comment by jeremyknox-ucsb** [comment]
# v3 Data Frames Created
Version 3 data frames have been created using [fix_old_retweets.R](https://github.com/Science-for-Nature-and-People/soc-twitter/blob/master/pre_processing/fix_old_retweets.R). Both RT and noRT data frames now have the following modifications:
- [ ] archive data (purchased data) no longer has NAs in "is_retweet" 
- [ ] in "text" any retweets with  "RT @xxxx:" have been edited so that they are identical to the original tweet 
# Complete

**Comment by brunj7** [comment]
great job ! Let us talk about the best strategy moving forward.
