### ISSUE TITLE
Starting date of the data set not consistent among versions

### ISSUE THREAD

**Issue by brunj7** [Science-for-Nature-and-People/soc-twitter#46]
@kylemonper noticed that version 3 of the data set only starts in 10/2007

**Comment by brunj7** [comment]
Already in version 2 there are discrepancies between Rt and NoRT dataset:

noRT starts in `2017-10-28 18:28:10 UTC`
RT starts in `2017-04-01 00:06:00 UTC`

raw data set the first tweet is `2006-11-30 21:41:09 UTC`

I am suspecting there is something wrong with our last retweet filtering

**Comment by brunj7** [comment]
ok wrong field used above the data does strat `2017-04-01 00:06:00 UTC`

**Comment by brunj7** [comment]
was looking at the scripts: https://github.com/Science-for-Nature-and-People/soc-twitter/blob/master/pre_processing/is_retweet.R

**Comment by kylemonper** [comment]
Still an issue with overlapping tweets within the noRT dataset:
![image](https://user-images.githubusercontent.com/43857085/78403412-28a84900-75b1-11ea-9eac-619711cef1f5.png)

**Comment by kylemonper** [comment]
also, the strange quotes in the query issue has returned:
![image](https://user-images.githubusercontent.com/43857085/78405640-c43bb880-75b5-11ea-8602-dbff41423407.png)

**Comment by kylemonper** [comment]
Was able to fix the above to bugs within the analysis code (probably still want to update the master though) and found no major/unexpected changes to our results figures

**Comment by brunj7** [comment]
ok great. We found the API itself is returning duplicates. We will run your block of code to fix this on the master

**Comment by brunj7** [comment]
Has been resolved by #48
